name: secret_gallery_3
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.9.0


dependencies:
  flutter:
    sdk: flutter

  math_expressions: ^2.6.1
  characters: ^1.3.0
  path_provider: ^2.1.5
  path: ^1.9.0
  photo_manager: ^3.5.1
  flutter_secure_storage: ^9.2.2
  cryptography: ^2.7.0
  cupertino_icons: ^1.0.8
  video_player: ^2.9.1
  video_thumbnail: ^0.5.3
  shared_preferences: ^2.3.2
  google_mobile_ads: ^6.0.0


dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: false  # ← iOSは無効
  image_path: "assets/icon.png"  # 使いたいアイコン画像のパス

flutter:


  uses-material-design: true
